// api/bot-proxy.js
import fs from 'fs';
import path from 'path';
import guidesData from '../src/data/guides.json' with { type: 'json' };

export default function handler(req, res) {
    const url = req.url;

    // 1. Locate the compiled index.html generated by Vite
    const filePath = path.join(process.cwd(), 'dist', 'index.html');
    let html = '';

    try {
        html = fs.readFileSync(filePath, 'utf8');
    } catch (err) {
        return res.status(500).send('Error reading index.html');
    }

    // 2. Default Metadata
    let title = "Generals IL | קהילת השחקנים הישראלית";
    let desc = "הצטרפו לקהילת Generals Zero Hour הישראלית – מדריכים, עדכונים, כלים, וקישורים חשובים למשחק.";

    // 3. Check if the bot is looking at a specific Guide
    if (url.startsWith('/guides/')) {
        const guideName = url.split('/')[2];
        const guide = guidesData.find(g => g.guideName === guideName);
        if (guide) {
            title = `${guide.title} | Generals IL`;
            desc = guide.description;
        }
    }

    // 4. Inject the dynamic metadata by replacing the defaults in index.html
    html = html.replace(/<title>.*<\/title>/, `<title>${title}</title>`);
    html = html.replace(/<meta name="description" content="[^"]*">/, `<meta name="description" content="${desc}">`);
    html = html.replace(/<meta property="og:title" content="[^"]*">/, `<meta property="og:title" content="${title}">`);
    html = html.replace(/<meta property="og:description" content="[^"]*">/, `<meta property="og:description" content="${desc}">`);
    html = html.replace(/<meta name="twitter:title" content="[^"]*">/, `<meta name="twitter:title" content="${title}">`);
    html = html.replace(/<meta name="twitter:description" content="[^"]*">/, `<meta name="twitter:description" content="${desc}">`);

    // 5. Serve the modified HTML to the bot
    res.setHeader('Content-Type', 'text/html; charset=utf-8');
    res.status(200).send(html);
}